/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicPerformanceReport {
  'examSummaries' : Array<ExamSummary>,
  'studentId' : string,
  'combinedGrade' : string,
  'combinedPercentage' : number,
  'sessionId' : string,
  'overallPassed' : boolean,
}
export interface AcademicSession {
  'id' : string,
  'endDate' : string,
  'sessionName' : string,
  'createdAt' : bigint,
  'isArchived' : boolean,
  'isActive' : boolean,
  'startDate' : string,
}
export interface ActivityEntry {
  'userName' : string,
  'actionType' : string,
  'description' : string,
  'timestamp' : bigint,
}
export interface AlumniRecord {
  'id' : string,
  'fullName' : string,
  'graduationYear' : string,
  'photoUrl' : [] | [string],
  'email' : [] | [string],
  'currentCity' : [] | [string],
  'mobile' : [] | [string],
  'currentOccupation' : [] | [string],
  'className' : string,
}
export interface AlumniRow {
  'id' : string,
  'fullName' : string,
  'graduationYear' : string,
  'photoUrl' : [] | [string],
  'email' : [] | [string],
  'currentCity' : [] | [string],
  'mobile' : [] | [string],
  'currentOccupation' : [] | [string],
  'className' : string,
}
export interface AppSettings {
  'gpayEnabled' : boolean,
  'payuEnabled' : boolean,
  'whatsappApiKey' : [] | [string],
  'whatsappApiUrl' : [] | [string],
  'activeTheme' : string,
  'razorpayEnabled' : boolean,
  'upiId' : [] | [string],
  'messageTemplates' : Array<[string, string]>,
  'dashboardBgUrl' : [] | [string],
}
export interface AppSettingsRow {
  'gpayEnabled' : boolean,
  'payuEnabled' : boolean,
  'whatsappApiKey' : [] | [string],
  'whatsappApiUrl' : [] | [string],
  'activeTheme' : string,
  'razorpayEnabled' : boolean,
  'upiId' : [] | [string],
  'messageTemplates' : Array<[string, string]>,
  'dashboardBgUrl' : [] | [string],
}
export interface AppUser {
  'id' : bigint,
  'username' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'passwordHash' : string,
}
export interface AttendanceBreakdownRow {
  'classLevelText' : string,
  'sectionName' : string,
  'totalCount' : bigint,
  'presentCount' : bigint,
  'sectionId' : string,
  'absentCount' : bigint,
}
export type AttendanceDevice = { 'QR' : null } |
  { 'Face' : null } |
  { 'RFID' : null } |
  { 'ESSLBiometric' : null };
export interface AttendanceRecord {
  'id' : string,
  'status' : AttendanceStatus,
  'studentId' : string,
  'date' : string,
  'markedBy' : string,
  'remarks' : [] | [string],
}
export interface AttendanceRow {
  'id' : string,
  'status' : AttendanceStatus,
  'studentId' : string,
  'date' : string,
  'markedBy' : string,
  'remarks' : [] | [string],
}
export type AttendanceStatus = { 'Leave' : null } |
  { 'Present' : null } |
  { 'Late' : null } |
  { 'Absent' : null };
export interface AttendanceSummaryToday {
  'totalStudents' : bigint,
  'totalStaff' : bigint,
  'presentStaff' : bigint,
  'presentStudents' : bigint,
}
export interface AttendanceSystemSettings {
  'qr' : boolean,
  'essl' : boolean,
  'face' : boolean,
  'rfid' : boolean,
}
export interface AuditLog {
  'id' : string,
  'action' : string,
  'moduleName' : string,
  'userId' : string,
  'timestamp' : bigint,
  'details' : string,
}
export interface BackupError {
  'recordId' : string,
  'entityType' : string,
  'reason' : string,
}
export interface BackupPayload {
  'alumniRecords' : Array<AlumniRow>,
  'staffLoans' : Array<StaffLoanRow>,
  'expenseHeads' : Array<ExpenseHead>,
  'libraryIssues' : Array<BookIssueRow>,
  'userAccounts' : Array<UserAccountRow>,
  'examTimetables' : Array<ExamTimetableRow>,
  'staffIncentives' : Array<StaffIncentiveRow>,
  'students' : Array<StudentRow>,
  'subjects' : Array<SubjectRow>,
  'notifications' : Array<NotificationRow>,
  'inventoryItems' : Array<InventoryItemRow>,
  'feeCollections' : Array<FeeCollectionRow>,
  'expenseEntries' : Array<ExpenseEntry>,
  'staffPayouts' : Array<StaffPayoutRow>,
  'subjectClassMaps' : Array<SubjectClassMapRow>,
  'syllabusContents' : Array<SyllabusContentRow>,
  'attendanceRecords' : Array<AttendanceRow>,
  'chatRooms' : Array<ChatRoomRow>,
  'classTimetables' : Array<ClassTimetable>,
  'studentOldBalances' : Array<StudentOldBalanceRow>,
  'staff' : Array<StaffRow>,
  'backupVersion' : string,
  'payrollRecords' : Array<PayrollRow>,
  'backupTimestamp' : bigint,
  'feeHeadings' : Array<FeeHeadingRow>,
  'sessions' : Array<SessionRow>,
  'studentDiscounts' : Array<StudentDiscountRow>,
  'appSettings' : AppSettingsRow,
  'staffAttendance' : Array<StaffAttendanceRecord>,
  'pickupPoints' : Array<PickupPointRow>,
  'subjectAssignments' : Array<SubjectAssignment>,
  'enhancedPayroll' : Array<EnhancedPayrollRow>,
  'inventoryTx' : Array<InventoryTxRow>,
  'deviceAttendance' : Array<DeviceAttendanceRecord>,
  'sections' : Array<SectionRow>,
  'syllabusChapters' : Array<SyllabusChapterRow>,
  'routes' : Array<RouteRow>,
  'faceEnrollments' : Array<FaceEnrollmentRecord>,
  'feePlans' : Array<FeePlanRow>,
  'schoolInfo' : SchoolInfoRow,
  'libraryBooks' : Array<BookRow>,
}
export type BackupSchedule = { 'never' : null } |
  { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface BackupSettings {
  'backupSchedule' : BackupSchedule,
  'lastBackupTimestamp' : bigint,
  'backupGmail' : [] | [string],
}
export interface Book {
  'id' : string,
  'title' : string,
  'availableCopies' : bigint,
  'isbn' : string,
  'publisher' : [] | [string],
  'photoUrl' : [] | [string],
  'author' : string,
  'totalCopies' : bigint,
  'category' : string,
  'shelfLocation' : [] | [string],
}
export interface BookIssue {
  'id' : string,
  'issueDate' : string,
  'status' : BookIssueStatus,
  'studentId' : string,
  'fine' : bigint,
  'dueDate' : string,
  'bookId' : string,
  'returnDate' : [] | [string],
}
export interface BookIssueRow {
  'id' : string,
  'issueDate' : string,
  'status' : BookIssueStatus,
  'studentId' : string,
  'fine' : bigint,
  'dueDate' : string,
  'bookId' : string,
  'returnDate' : [] | [string],
}
export type BookIssueStatus = { 'Overdue' : null } |
  { 'Issued' : null } |
  { 'Returned' : null };
export interface BookRow {
  'id' : string,
  'title' : string,
  'availableCopies' : bigint,
  'isbn' : string,
  'publisher' : [] | [string],
  'photoUrl' : [] | [string],
  'author' : string,
  'totalCopies' : bigint,
  'category' : string,
  'shelfLocation' : [] | [string],
}
export interface BusLocation {
  'latitude' : number,
  'isActive' : boolean,
  'routeName' : string,
  'updatedAt' : bigint,
  'routeId' : string,
  'longitude' : number,
  'busId' : string,
  'driverName' : string,
}
export interface CalendarStats {
  'holidayCount' : bigint,
  'workingDays' : bigint,
  'sundayCount' : bigint,
  'totalDaysFromApril1' : bigint,
}
export interface CellCopyOp {
  'source' : TimetableCellRef,
  'target' : TimetableCellRef,
}
export interface CertificateTemplate {
  'id' : string,
  'name' : string,
  'createdBy' : string,
  'templateType' : string,
  'updatedAt' : bigint,
  'isDefault' : boolean,
  'layoutJson' : string,
}
export interface CertificateTemplate__1 {
  'id' : string,
  'thumbnail' : string,
  'elementsJson' : string,
  'name' : string,
  'createdBy' : string,
  'templateType' : string,
  'updatedAt' : bigint,
  'isDefault' : boolean,
}
export interface ChapterWithQA {
  'qas' : Array<QAPair>,
  'title' : string,
  'chapterId' : string,
  'chapterNo' : bigint,
  'userProvidedQuestions' : Array<string>,
  'approvalStatus' : string,
  'completionPercent' : bigint,
  'topics' : Array<string>,
  'subjectId' : string,
  'classLevel' : string,
}
export interface ChatMessage {
  'id' : string,
  'attachmentUrl' : [] | [string],
  'isDeleted' : boolean,
  'content' : string,
  'sentAt' : bigint,
  'roomId' : string,
  'senderId' : string,
}
export interface ChatRoom {
  'id' : string,
  'members' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'roomType' : ChatRoomType,
}
export interface ChatRoomRow {
  'id' : string,
  'members' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'roomType' : ChatRoomType,
}
export type ChatRoomType = { 'General' : null } |
  { 'RouteGroup' : null } |
  { 'ClassGroup' : null } |
  { 'Direct' : null };
export type ClassLevel = { 'LKG' : null } |
  { 'UKG' : null } |
  { 'Class10' : null } |
  { 'Class11' : null } |
  { 'Class12' : null } |
  { 'Class1' : null } |
  { 'Class2' : null } |
  { 'Class3' : null } |
  { 'Class4' : null } |
  { 'Class5' : null } |
  { 'Class6' : null } |
  { 'Class7' : null } |
  { 'Class8' : null } |
  { 'Class9' : null } |
  { 'PlayWay' : null };
export type ClassLevelV = { 'LKG' : null } |
  { 'UKG' : null } |
  { 'Class10' : null } |
  { 'Class11' : null } |
  { 'Class12' : null } |
  { 'Class1' : null } |
  { 'Class2' : null } |
  { 'Class3' : null } |
  { 'Class4' : null } |
  { 'Class5' : null } |
  { 'Class6' : null } |
  { 'Class7' : null } |
  { 'Class8' : null } |
  { 'Class9' : null } |
  { 'PlayWay' : null };
export interface ClassLinks {
  'sectionName' : string,
  'broadcastUrl' : string,
  'classLevel' : string,
  'cctvUrl' : string,
}
export interface ClassTimetable {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'periodConfigs' : [] | [Array<PeriodConfig>],
  'entries' : Array<ClassTimetableEntry>,
  'updatedAt' : bigint,
  'sessionId' : string,
}
export interface ClassTimetableEntry {
  'startTime' : string,
  'endTime' : string,
  'subjectName' : string,
  'sectionName' : string,
  'dayOfWeek' : string,
  'teacherStaffId' : string,
  'teacherName' : string,
  'periodNumber' : bigint,
  'classLevel' : ClassLevel,
}
export interface CustomLink {
  'url' : string,
  'linkLabel' : string,
  'order' : bigint,
  'isExternal' : boolean,
}
export interface DailySalesSummary {
  'date' : string,
  'totalSales' : bigint,
  'totalAmount' : number,
  'itemsSold' : bigint,
}
export interface DashboardStatsV2 {
  'totalClasses' : bigint,
  'feesCollectedToday' : bigint,
  'totalStudents' : bigint,
  'recentActivity' : Array<ActivityEntry>,
  'totalStaff' : bigint,
  'feesCollectedThisMonth' : bigint,
  'feesCollectedThisYear' : bigint,
  'pendingFeesTotal' : bigint,
  'attendanceTodayPercent' : [] | [number],
  'feesCollectedTodayBreakdown' : Array<FeePaymentSummary>,
  'totalSections' : bigint,
}
export interface DemandRegisterEntry {
  'studentId' : string,
  'admNo' : string,
  'studentName' : string,
  'section' : string,
  'totalDue' : bigint,
  'fatherName' : string,
  'oldBalance' : bigint,
  'duesPerHeading' : Array<[string, string, bigint]>,
  'phone' : string,
  'months' : Array<string>,
  'className' : string,
}
export interface DemandRegisterFilter {
  'sectionFilter' : [] | [string],
  'sessionId' : string,
  'months' : Array<string>,
  'headingIds' : Array<string>,
  'classFilter' : [] | [string],
}
export interface DeviceAttendanceRecord {
  'id' : bigint,
  'status' : string,
  'studentId' : bigint,
  'studentName' : string,
  'date' : string,
  'section' : string,
  'inTime' : [] | [string],
  'classLevel' : ClassLevel,
  'deviceType' : AttendanceDevice,
  'outTime' : [] | [string],
}
export interface DeviceConfig {
  'port' : [] | [bigint],
  'updatedAt' : bigint,
  'usbPort' : [] | [string],
  'deviceId' : [] | [string],
  'deviceType' : string,
  'ipAddress' : [] | [string],
}
export interface DirectMessage {
  'id' : string,
  'toClassLevel' : [] | [string],
  'deliveryStatus' : string,
  'sentAt' : string,
  'templateKey' : [] | [string],
  'toStudentId' : [] | [string],
  'toSection' : [] | [string],
  'message' : string,
  'fromUsername' : string,
  'channel' : string,
}
export interface EnhancedPayrollRecord {
  'id' : string,
  'month' : string,
  'incentives' : number,
  'paymentStatus' : string,
  'staffId' : string,
  'generatedAt' : bigint,
  'loanDeduction' : number,
  'deductions' : number,
  'netSalary' : number,
  'payslipNotes' : string,
  'attendanceDays' : number,
  'grossSalary' : number,
  'workingDays' : number,
  'advancePaid' : number,
  'absentDays' : number,
  'payouts' : Array<StaffPayout>,
  'deductibleDays' : number,
}
export interface EnhancedPayrollRow {
  'id' : string,
  'month' : string,
  'incentives' : number,
  'paymentStatus' : string,
  'staffId' : string,
  'generatedAt' : bigint,
  'loanDeduction' : number,
  'deductions' : number,
  'netSalary' : number,
  'payslipNotes' : string,
  'attendanceDays' : number,
  'grossSalary' : number,
  'workingDays' : number,
  'advancePaid' : number,
  'absentDays' : number,
  'payouts' : Array<StaffPayoutRow>,
  'deductibleDays' : number,
}
export interface ExamCalendarEntry {
  'id' : string,
  'date' : string,
  'createdAt' : bigint,
  'examName' : string,
  'className' : string,
}
export interface ExamConfig {
  'id' : string,
  'weightage' : number,
  'subjectConfigs' : Array<ExamSubjectConfig>,
  'includeInCombined' : boolean,
  'createdAt' : bigint,
  'classId' : string,
  'sessionId' : string,
  'examName' : string,
}
export interface ExamResult {
  'id' : string,
  'totalMarks' : bigint,
  'studentId' : string,
  'scores' : Array<[string, bigint]>,
  'rank' : [] | [bigint],
  'examTimetableId' : string,
  'grade' : string,
  'remarks' : [] | [string],
  'percentage' : number,
}
export interface ExamResultV2 {
  'id' : string,
  'subjectMarks' : Array<SubjectMarkEntry>,
  'examConfigId' : string,
  'studentId' : string,
  'overallGrade' : string,
  'rank' : [] | [bigint],
  'classId' : string,
  'totalObtained' : number,
  'totalMax' : number,
  'savedAt' : bigint,
  'sessionId' : string,
  'overallPassed' : boolean,
  'examName' : string,
  'remarks' : [] | [string],
  'percentage' : number,
}
export interface ExamScheduleEntry {
  'startTime' : string,
  'endTime' : string,
  'date' : string,
  'room' : [] | [string],
  'subjectId' : string,
  'invigilatorId' : [] | [string],
}
export interface ExamScheduleEntryRow {
  'startTime' : string,
  'endTime' : string,
  'date' : string,
  'room' : [] | [string],
  'subjectId' : string,
  'invigilatorId' : [] | [string],
}
export interface ExamSubjectConfig {
  'subjectName' : string,
  'subjectId' : string,
  'maxMarks' : number,
  'passingMarks' : number,
}
export interface ExamSummary {
  'subjectMarks' : Array<SubjectMarkEntry>,
  'examConfigId' : string,
  'overallGrade' : string,
  'overallPassed' : boolean,
  'examName' : string,
  'percentage' : number,
}
export interface ExamTimetable {
  'id' : string,
  'session' : string,
  'classLevel' : ClassLevel,
  'schedule' : Array<ExamScheduleEntry>,
  'examName' : string,
}
export interface ExamTimetableRow {
  'id' : string,
  'session' : string,
  'classLevel' : ClassLevel,
  'schedule' : Array<ExamScheduleEntryRow>,
  'examName' : string,
}
export type ExpHeadType = { 'Income' : null } |
  { 'Expense' : null };
export interface ExpenseEntry {
  'id' : string,
  'date' : string,
  'createdAt' : string,
  'createdBy' : string,
  'description' : string,
  'amount' : number,
  'headId' : string,
}
export interface ExpenseEntry__1 {
  'id' : string,
  'receipt' : [] | [string],
  'date' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'description' : string,
  'amount' : bigint,
  'headId' : string,
}
export interface ExpenseHead {
  'id' : string,
  'name' : string,
  'createdAt' : string,
  'color' : string,
  'type' : string,
}
export interface ExpenseHead__1 {
  'id' : string,
  'headType' : ExpHeadType,
  'name' : string,
  'description' : [] | [string],
}
export interface ExpenseStats {
  'balance' : number,
  'totalIncome' : number,
  'totalExpense' : number,
}
export interface FaceEnrollmentRecord {
  'studentId' : string,
  'admNo' : string,
  'descriptorJson' : string,
  'faceEnrollmentDate' : [] | [string],
  'photoUrl' : [] | [string],
  'updatedAt' : bigint,
  'enrolledBy' : string,
  'faceEnrolled' : boolean,
}
export interface FeeAuditLog {
  'id' : string,
  'action' : string,
  'oldValue' : string,
  'studentId' : string,
  'newValue' : string,
  'adminName' : string,
  'paymentId' : string,
  'timestamp' : bigint,
  'adminId' : string,
  'fieldChanged' : string,
}
export interface FeeCollectionRow {
  'id' : string,
  'isDeleted' : boolean,
  'studentId' : string,
  'balance' : bigint,
  'balanceCarriedForward' : number,
  'createdAt' : bigint,
  'createdBy' : string,
  'totalDue' : bigint,
  'upiRef' : [] | [string],
  'lateFees' : bigint,
  'totalAmount' : bigint,
  'paymentDate' : string,
  'otherFee' : [] | [OtherFeeRow],
  'paymentMode' : string,
  'receiptNo' : string,
  'sessionId' : string,
  'items' : Array<FeePaymentItemRow>,
  'remarks' : [] | [string],
  'discountTotal' : bigint,
}
export interface FeeHeading {
  'id' : string,
  'applicableMonths' : Array<string>,
  'name' : string,
  'description' : [] | [string],
  'isActive' : boolean,
}
export interface FeeHeadingRow {
  'id' : string,
  'applicableMonths' : Array<string>,
  'name' : string,
  'description' : [] | [string],
  'isActive' : boolean,
}
export interface FeePayment {
  'id' : string,
  'isDeleted' : boolean,
  'studentId' : string,
  'balance' : bigint,
  'balanceCarriedForward' : number,
  'createdAt' : bigint,
  'createdBy' : string,
  'totalDue' : bigint,
  'upiRef' : [] | [string],
  'lateFees' : bigint,
  'totalAmount' : bigint,
  'paymentDate' : string,
  'otherFee' : [] | [OtherFee],
  'paymentMode' : string,
  'receiptNo' : string,
  'sessionId' : string,
  'items' : Array<FeePaymentItem>,
  'remarks' : [] | [string],
  'discountTotal' : bigint,
}
export interface FeePaymentEntry {
  'id' : string,
  'isDeleted' : boolean,
  'studentId' : string,
  'collectedBy' : string,
  'totalAmount' : bigint,
  'paymentDate' : string,
  'receiptNo' : string,
}
export interface FeePaymentItem {
  'month' : string,
  'headingId' : string,
  'amount' : bigint,
}
export interface FeePaymentItemRow {
  'month' : string,
  'headingId' : string,
  'amount' : bigint,
}
export interface FeePaymentSummary {
  'admNo' : string,
  'studentName' : string,
  'receiverName' : string,
  'paymentMode' : string,
  'receiptNo' : string,
  'amount' : bigint,
  'className' : string,
}
export interface FeePaymentUpdate {
  'totalAmount' : [] | [number],
  'paymentDate' : [] | [string],
  'paymentMode' : [] | [string],
}
export interface FeePlan {
  'id' : string,
  'monthlyAmounts' : Array<[string, bigint]>,
  'sectionId' : [] | [string],
  'session' : string,
  'classLevel' : ClassLevel,
}
export interface FeePlanRow {
  'id' : string,
  'monthlyAmounts' : Array<[string, bigint]>,
  'sectionId' : [] | [string],
  'session' : string,
  'classLevel' : ClassLevel,
}
export interface FeeRegisterBalanceEntry {
  'id' : string,
  'studentId' : string,
  'collectedBy' : string,
  'totalAmount' : bigint,
  'paymentDate' : string,
  'receiptNo' : string,
  'previousBalance' : number,
}
export interface FeeRegisterEntry {
  'id' : string,
  'studentId' : string,
  'balance' : bigint,
  'studentName' : string,
  'sectionName' : string,
  'collectedBy' : string,
  'totalDue' : bigint,
  'lateFees' : bigint,
  'totalAmount' : bigint,
  'paymentDate' : string,
  'paymentMode' : string,
  'receiptNo' : string,
  'sessionId' : string,
  'months' : Array<string>,
  'className' : string,
  'previousBalance' : number,
  'discountTotal' : bigint,
}
export interface FullPayrollRecord {
  'id' : string,
  'status' : string,
  'month' : string,
  'incentives' : number,
  'staffName' : string,
  'staffId' : string,
  'dailyRate' : number,
  'createdAt' : bigint,
  'year' : string,
  'freeLeaves' : bigint,
  'netSalary' : number,
  'daysAbsent' : bigint,
  'deductionAmount' : number,
  'updatedAt' : bigint,
  'daysPresent' : bigint,
  'workingDays' : bigint,
  'basicSalary' : number,
  'deductibleDays' : bigint,
}
export interface GenerateScheduleParams {
  'startTime' : string,
  'endDate' : string,
  'endTime' : string,
  'classSubjects' : Array<[ClassLevel, Array<string>]>,
  'sessionId' : string,
  'examName' : string,
  'participatingClasses' : Array<ClassLevel>,
  'startDate' : string,
}
export interface GenerateTimetableParams {
  'periodStartTimes' : Array<string>,
  'classSections' : Array<[ClassLevel, string]>,
  'name' : string,
  'periodConfigs' : [] | [Array<PeriodConfig>],
  'periodEndTimes' : Array<string>,
  'periodsPerDay' : bigint,
  'sessionId' : string,
  'workDays' : Array<string>,
}
export interface Holiday {
  'id' : string,
  'isRecurring' : boolean,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface HomeworkEntry {
  'id' : string,
  'attachmentUrl' : [] | [string],
  'title' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'dueDate' : string,
  'description' : string,
  'sectionId' : [] | [string],
  'subjectId' : string,
  'classLevel' : ClassLevel,
}
export interface HomeworkSubmission {
  'id' : string,
  'attachmentUrl' : [] | [string],
  'content' : [] | [string],
  'studentId' : string,
  'homeworkId' : string,
  'submittedAt' : bigint,
  'feedback' : [] | [string],
  'grade' : [] | [string],
}
export interface IndexPageConfig {
  'customLinks' : Array<CustomLink>,
  'isPublished' : boolean,
  'ctaButtonText' : string,
  'ctaButtonColor' : string,
  'heroSubtitle' : string,
  'heroTextColor' : string,
  'heroImageFileId' : string,
  'heroBgColor' : string,
  'sections' : Array<IndexPageSection>,
  'heroTitle' : string,
}
export interface IndexPageSection {
  'id' : string,
  'title' : string,
  'order' : bigint,
  'sectionType' : string,
  'description' : string,
  'isVisible' : boolean,
  'imageFileId' : string,
  'textColor' : string,
  'bgColor' : string,
}
export type InvTxType = { 'Sale' : null } |
  { 'Purchase' : null } |
  { 'Adjustment' : null };
export interface InventoryItem {
  'id' : string,
  'purchasePrice' : bigint,
  'name' : string,
  'unit' : string,
  'minStock' : bigint,
  'store' : string,
  'category' : string,
  'salePrice' : bigint,
  'currentStock' : bigint,
}
export interface InventoryItemRow {
  'id' : string,
  'purchasePrice' : bigint,
  'name' : string,
  'unit' : string,
  'minStock' : bigint,
  'store' : string,
  'category' : string,
  'salePrice' : bigint,
  'currentStock' : bigint,
}
export interface InventoryTransaction {
  'id' : string,
  'itemId' : string,
  'balanceAmount' : bigint,
  'transactionType' : InvTxType,
  'date' : string,
  'createdBy' : string,
  'receivedAmount' : bigint,
  'sellerName' : string,
  'totalAmount' : bigint,
  'quantity' : bigint,
  'buyerAdmNo' : string,
  'buyerName' : string,
  'unitPrice' : bigint,
  'remarks' : [] | [string],
}
export interface InventoryTxRow {
  'id' : string,
  'itemId' : string,
  'balanceAmount' : bigint,
  'transactionType' : InvTxType,
  'date' : string,
  'createdBy' : string,
  'receivedAmount' : bigint,
  'sellerName' : string,
  'totalAmount' : bigint,
  'quantity' : bigint,
  'buyerAdmNo' : string,
  'buyerName' : string,
  'unitPrice' : bigint,
  'remarks' : [] | [string],
}
export interface MCQQuestion {
  'id' : string,
  'marks' : bigint,
  'correctOption' : bigint,
  'question' : string,
  'options' : Array<string>,
}
export interface ModulePermission {
  'moduleId' : string,
  'canExport' : boolean,
  'canEdit' : boolean,
  'canView' : boolean,
  'canDelete' : boolean,
  'canCreate' : boolean,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'notifType' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'isRead' : boolean,
  'targetClassLevel' : [] | [ClassLevel],
  'targetStudentId' : [] | [string],
  'message' : string,
  'targetRole' : [] | [string],
}
export interface NotificationRow {
  'id' : string,
  'title' : string,
  'notifType' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'isRead' : boolean,
  'targetClassLevel' : [] | [ClassLevel],
  'targetStudentId' : [] | [string],
  'message' : string,
  'targetRole' : [] | [string],
}
export interface OnlineExam {
  'id' : string,
  'startTime' : [] | [string],
  'title' : string,
  'endTime' : [] | [string],
  'createdBy' : string,
  'isActive' : boolean,
  'durationMinutes' : bigint,
  'subjectId' : [] | [string],
  'questions' : Array<MCQQuestion>,
  'classLevel' : ClassLevel,
}
export interface OnlineExamSubmission {
  'id' : string,
  'totalMarks' : bigint,
  'studentId' : string,
  'answers' : Array<[string, bigint]>,
  'submittedAt' : bigint,
  'score' : bigint,
  'timeTakenSecs' : bigint,
  'examId' : string,
}
export interface OtherFee { 'description' : string, 'amount' : bigint }
export interface OtherFeeRow { 'description' : string, 'amount' : bigint }
export interface PaidLeaveConfig {
  'updatedAt' : bigint,
  'daysPerMonth' : number,
}
export interface PayrollCalculation {
  'month' : bigint,
  'faceCount' : bigint,
  'staffName' : string,
  'staffId' : string,
  'presentDays' : bigint,
  'year' : bigint,
  'netPay' : bigint,
  'monthlySalary' : bigint,
  'rfidCount' : bigint,
  'workingDays' : bigint,
  'absentDays' : bigint,
  'qrCount' : bigint,
  'biometricCount' : bigint,
}
export type PayrollMonthStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export interface PayrollRecord {
  'id' : string,
  'status' : PayrollStatus,
  'month' : string,
  'staffId' : string,
  'generatedBy' : string,
  'presentDays' : bigint,
  'year' : string,
  'deductions' : bigint,
  'netSalary' : bigint,
  'totalDays' : bigint,
  'additions' : bigint,
  'paymentDate' : [] | [string],
  'basicSalary' : bigint,
}
export interface PayrollRow {
  'id' : string,
  'status' : PayrollStatus,
  'month' : string,
  'staffId' : string,
  'generatedBy' : string,
  'presentDays' : bigint,
  'year' : string,
  'deductions' : bigint,
  'netSalary' : bigint,
  'totalDays' : bigint,
  'additions' : bigint,
  'paymentDate' : [] | [string],
  'basicSalary' : bigint,
}
export type PayrollStatus = { 'Paid' : null } |
  { 'Pending' : null };
export interface PeriodConfig {
  'startTime' : string,
  'durationMinutes' : bigint,
  'periodNumber' : bigint,
  'isInterval' : boolean,
}
export interface PickupPoint {
  'id' : string,
  'timing' : string,
  'order' : bigint,
  'name' : string,
  'routeId' : string,
  'monthlyFare' : number,
}
export interface PickupPointRow {
  'id' : string,
  'timing' : string,
  'order' : bigint,
  'name' : string,
  'routeId' : string,
  'monthlyFare' : number,
}
export type PromClassLevel = { 'LKG' : null } |
  { 'UKG' : null } |
  { 'Class10' : null } |
  { 'Class11' : null } |
  { 'Class12' : null } |
  { 'Class1' : null } |
  { 'Class2' : null } |
  { 'Class3' : null } |
  { 'Class4' : null } |
  { 'Class5' : null } |
  { 'Class6' : null } |
  { 'Class7' : null } |
  { 'Class8' : null } |
  { 'Class9' : null } |
  { 'PlayWay' : null };
export interface PromotionAllResult {
  'totalPromoted' : bigint,
  'breakdown' : Array<PromotionClassBreakdown>,
  'totalGraduated' : bigint,
  'totalFailed' : bigint,
}
export interface PromotionClassBreakdown {
  'graduated' : bigint,
  'className' : string,
  'failed' : bigint,
  'promoted' : bigint,
}
export interface PromotionPreviewItem {
  'studentId' : string,
  'admNo' : string,
  'discountCount' : bigint,
  'fullName' : string,
  'oldBalance' : number,
  'hasTransport' : boolean,
}
export interface PromotionResult {
  'errors' : Array<string>,
  'failed' : bigint,
  'promoted' : bigint,
}
export interface QAPair { 'question' : string, 'answer' : string }
export interface QAPairRow { 'question' : string, 'answer' : string }
export interface RestoreResult {
  'errors' : Array<BackupError>,
  'successCount' : bigint,
  'message' : string,
  'recordCounts' : RestoreStats,
  'success' : boolean,
  'failCount' : bigint,
  'skippedCount' : bigint,
}
export interface RestoreStats {
  'alumniRecords' : bigint,
  'staffLoans' : bigint,
  'expenseHeads' : bigint,
  'total' : bigint,
  'libraryIssues' : bigint,
  'userAccounts' : bigint,
  'examTimetables' : bigint,
  'staffIncentives' : bigint,
  'students' : bigint,
  'subjects' : bigint,
  'notifications' : bigint,
  'inventory' : bigint,
  'feeCollections' : bigint,
  'expenseEntries' : bigint,
  'staffPayouts' : bigint,
  'subjectClassMaps' : bigint,
  'syllabusContents' : bigint,
  'chatRooms' : bigint,
  'classTimetables' : bigint,
  'studentOldBalances' : bigint,
  'staff' : bigint,
  'payrollRecords' : bigint,
  'feeHeadings' : bigint,
  'sessions' : bigint,
  'attendance' : bigint,
  'studentDiscounts' : bigint,
  'staffAttendance' : bigint,
  'pickupPoints' : bigint,
  'subjectAssignments' : bigint,
  'enhancedPayroll' : bigint,
  'inventoryTx' : bigint,
  'deviceAttendance' : bigint,
  'sections' : bigint,
  'syllabusChapters' : bigint,
  'routes' : bigint,
  'faceEnrollments' : bigint,
  'feePlans' : bigint,
  'libraryBooks' : bigint,
}
export interface RolePermissions {
  'role' : UserRole,
  'modulePermissions' : Array<ModulePermission>,
}
export interface RoomRec {
  'id' : string,
  'members' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'roomType' : { 'General' : null } |
    { 'RouteGroup' : null } |
    { 'ClassGroup' : null } |
    { 'Direct' : null },
}
export interface RouteRow {
  'id' : string,
  'driverMobile' : string,
  'routeName' : string,
  'routeNo' : string,
  'busNo' : string,
  'capacity' : bigint,
  'driverName' : string,
}
export interface SchoolInfo {
  'about' : string,
  'name' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'website' : [] | [string],
  'address' : string,
  'phone' : string,
}
export interface SchoolInfoRow {
  'about' : string,
  'name' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'website' : [] | [string],
  'address' : string,
  'phone' : string,
}
export interface Section {
  'id' : string,
  'sectionName' : string,
  'teacherId' : [] | [string],
  'classLevel' : ClassLevel,
  'roomNo' : [] | [string],
}
export interface SectionRow {
  'id' : string,
  'sectionName' : string,
  'teacherId' : [] | [string],
  'classLevel' : ClassLevel,
  'roomNo' : [] | [string],
}
export interface SessionRow {
  'id' : string,
  'endDate' : string,
  'sessionName' : string,
  'createdAt' : bigint,
  'isArchived' : boolean,
  'isActive' : boolean,
  'startDate' : string,
}
export interface SmartExamTimetable {
  'id' : bigint,
  'startTime' : string,
  'status' : string,
  'endDate' : string,
  'endTime' : string,
  'entries' : Array<SmartTimetableEntry>,
  'sessionId' : string,
  'examName' : string,
  'participatingClasses' : Array<ClassLevel>,
  'startDate' : string,
}
export interface SmartTimetableEntry {
  'day' : string,
  'subjectName' : string,
  'date' : string,
  'isLocked' : boolean,
  'classLevel' : ClassLevel,
  'position' : bigint,
}
export interface Staff {
  'id' : string,
  'status' : StaffStatus,
  'salary' : bigint,
  'bankAccount' : [] | [string],
  'ifscCode' : [] | [string],
  'designation' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'photoUrl' : [] | [string],
  'email' : [] | [string],
  'dateOfJoining' : string,
  'aadhaarNo' : [] | [string],
  'employeeId' : string,
  'address' : string,
  'mobile' : string,
  'department' : string,
}
export interface StaffAttBreakdown {
  'staffList' : Array<
    {
      'status' : string,
      'staffId' : string,
      'name' : string,
      'inTime' : [] | [string],
      'outTime' : [] | [string],
    }
  >,
  'totalCount' : bigint,
  'presentCount' : bigint,
}
export interface StaffAttendanceRecord {
  'id' : bigint,
  'month' : bigint,
  'staffName' : string,
  'staffId' : string,
  'date' : string,
  'year' : bigint,
  'inTime' : [] | [string],
  'deviceType' : AttendanceDevice,
  'outTime' : [] | [string],
}
export interface StaffIncentive {
  'id' : string,
  'month' : string,
  'staffId' : string,
  'approvedBy' : string,
  'createdAt' : bigint,
  'year' : string,
  'amount' : number,
  'reason' : string,
}
export interface StaffIncentiveRow {
  'id' : string,
  'month' : string,
  'staffId' : string,
  'approvedBy' : string,
  'createdAt' : bigint,
  'year' : string,
  'amount' : number,
  'reason' : string,
}
export interface StaffLoan {
  'id' : string,
  'remainingAmount' : number,
  'startMonth' : string,
  'staffId' : string,
  'createdAt' : bigint,
  'monthlyDeduction' : number,
  'notes' : string,
  'principalAmount' : number,
}
export interface StaffLoanRow {
  'id' : string,
  'remainingAmount' : number,
  'startMonth' : string,
  'staffId' : string,
  'createdAt' : bigint,
  'monthlyDeduction' : number,
  'notes' : string,
  'principalAmount' : number,
}
export interface StaffPaymentSummaryEntry {
  'status' : string,
  'month' : string,
  'netSalary' : [] | [number],
  'amountPaid' : number,
}
export interface StaffPayout {
  'id' : string,
  'staffId' : string,
  'date' : string,
  'mode' : string,
  'createdAt' : bigint,
  'recordedBy' : string,
  'notes' : string,
  'amount' : number,
}
export interface StaffPayoutRow {
  'id' : string,
  'staffId' : string,
  'date' : string,
  'mode' : string,
  'createdAt' : bigint,
  'recordedBy' : string,
  'notes' : string,
  'amount' : number,
}
export interface StaffPayrollRecord {
  'id' : string,
  'status' : PayrollMonthStatus,
  'month' : bigint,
  'staffId' : string,
  'generatedAt' : bigint,
  'presentDays' : bigint,
  'deduction' : bigint,
  'year' : bigint,
  'freeLeave' : bigint,
  'netPay' : bigint,
  'amountPaid' : bigint,
  'lockedAt' : [] | [bigint],
  'notes' : string,
  'workingDays' : bigint,
  'absentDays' : bigint,
  'baseSalary' : bigint,
  'deductibleDays' : bigint,
}
export interface StaffRow {
  'id' : string,
  'status' : StaffStatus,
  'salary' : bigint,
  'bankAccount' : [] | [string],
  'ifscCode' : [] | [string],
  'designation' : string,
  'createdAt' : bigint,
  'fullName' : string,
  'photoUrl' : [] | [string],
  'email' : [] | [string],
  'dateOfJoining' : string,
  'aadhaarNo' : [] | [string],
  'employeeId' : string,
  'address' : string,
  'mobile' : string,
  'department' : string,
}
export type StaffStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface StaffYearEndSummary {
  'totalDeductions' : number,
  'totalEarned' : number,
  'totalPaid' : number,
  'monthsUnpaid' : bigint,
  'monthsPartiallyPaid' : bigint,
  'monthsFullyPaid' : bigint,
  'totalIncentives' : number,
}
export interface Student {
  'id' : string,
  'status' : StudentStatus,
  'transportPickupPointId' : [] | [string],
  'admNo' : string,
  'dateOfBirth' : string,
  'prevSchool' : [] | [string],
  'admissionDate' : [] | [string],
  'createdAt' : bigint,
  'srNo' : [] | [string],
  'fullName' : string,
  'motherName' : string,
  'photoUrl' : [] | [string],
  'permanentAddress' : string,
  'aadhaarNo' : [] | [string],
  'sectionId' : string,
  'session' : string,
  'fatherName' : string,
  'bloodGroup' : [] | [string],
  'gender' : string,
  'apaarNo' : [] | [string],
  'currentAddress' : string,
  'category' : [] | [string],
  'classLevel' : ClassLevel,
  'busNo' : [] | [string],
  'motherMobile' : [] | [string],
  'mobile' : [] | [string],
  'penNo' : [] | [string],
  'religion' : [] | [string],
  'transportRouteId' : [] | [string],
  'fatherMobile' : string,
}
export interface StudentDiscount {
  'id' : string,
  'remark' : [] | [string],
  'studentId' : string,
  'createdAt' : bigint,
  'headingId' : string,
  'amount' : bigint,
}
export interface StudentDiscountRow {
  'id' : string,
  'remark' : [] | [string],
  'studentId' : string,
  'createdAt' : bigint,
  'headingId' : string,
  'amount' : bigint,
}
export interface StudentFeeCollectionData {
  'previousYearDue' : number,
  'transportPickupPointId' : [] | [string],
  'studentId' : string,
  'admNo' : string,
  'studentName' : string,
  'payments' : Array<FeePayment>,
  'sectionName' : string,
  'feePlan' : [] | [FeePlan],
  'discounts' : Array<StudentDiscount>,
  'photoUrl' : [] | [string],
  'totalPaid' : bigint,
  'transportMonthlyFare' : number,
  'fatherName' : string,
  'oldBalanceAmount' : number,
  'transportRouteId' : [] | [string],
  'className' : string,
  'fatherMobile' : string,
  'inventoryDue' : bigint,
}
export interface StudentOldBalance {
  'id' : string,
  'previousYearDue' : [] | [number],
  'studentId' : string,
  'addedAt' : bigint,
  'sessionId' : string,
  'amount' : number,
}
export interface StudentOldBalanceRow {
  'id' : string,
  'studentId' : string,
  'addedAt' : bigint,
  'sessionId' : string,
  'amount' : number,
}
export interface StudentRow {
  'id' : string,
  'status' : StudentStatus,
  'transportPickupPointId' : [] | [string],
  'admNo' : string,
  'dateOfBirth' : string,
  'prevSchool' : [] | [string],
  'admissionDate' : [] | [string],
  'createdAt' : bigint,
  'srNo' : [] | [string],
  'fullName' : string,
  'motherName' : string,
  'photoUrl' : [] | [string],
  'permanentAddress' : string,
  'aadhaarNo' : [] | [string],
  'sectionId' : string,
  'session' : string,
  'fatherName' : string,
  'bloodGroup' : [] | [string],
  'gender' : string,
  'apaarNo' : [] | [string],
  'currentAddress' : string,
  'category' : [] | [string],
  'classLevel' : ClassLevel,
  'busNo' : [] | [string],
  'motherMobile' : [] | [string],
  'mobile' : [] | [string],
  'penNo' : [] | [string],
  'religion' : [] | [string],
  'transportRouteId' : [] | [string],
  'fatherMobile' : string,
}
export type StudentStatus = { 'Discontinued' : null } |
  { 'Active' : null } |
  { 'Graduated' : null };
export interface StudentWithPickupPoint {
  'student' : Student,
  'pickupPoint' : [] | [PickupPoint],
}
export interface Subject {
  'id' : string,
  'code' : string,
  'name' : string,
  'maxMarks' : bigint,
  'classLevel' : ClassLevel,
  'passingMarks' : bigint,
}
export interface SubjectAssignment {
  'id' : string,
  'staffId' : string,
  'subjectName' : string,
  'minClass' : [] | [string],
  'createdAt' : bigint,
  'session' : string,
  'subjectId' : string,
  'maxClass' : [] | [string],
}
export interface SubjectClassMap {
  'classLevels' : Array<ClassLevel>,
  'subjectId' : string,
}
export interface SubjectClassMapRow {
  'classLevels' : Array<ClassLevel>,
  'subjectId' : string,
}
export interface SubjectMarkEntry {
  'subjectName' : string,
  'marksObtained' : number,
  'isPassed' : boolean,
  'grade' : string,
  'subjectId' : string,
  'maxMarks' : number,
  'passingMarks' : number,
}
export interface SubjectRow {
  'id' : string,
  'code' : string,
  'name' : string,
  'maxMarks' : bigint,
  'classLevel' : ClassLevel,
  'passingMarks' : bigint,
}
export interface SyllabusChapter {
  'id' : string,
  'title' : string,
  'chapterNo' : bigint,
  'completionPercent' : bigint,
  'topics' : Array<string>,
  'subjectId' : string,
  'classLevel' : string,
}
export interface SyllabusChapterRow {
  'id' : string,
  'title' : string,
  'chapterNo' : bigint,
  'completionPercent' : bigint,
  'topics' : Array<string>,
  'subjectId' : string,
  'classLevel' : string,
}
export interface SyllabusContent {
  'contentText' : string,
  'generatedQA' : Array<QAPair>,
  'approvedAt' : [] | [bigint],
  'rejectionReason' : [] | [string],
  'submittedAt' : [] | [bigint],
  'chapterId' : string,
  'userProvidedQuestions' : Array<string>,
  'approvalStatus' : string,
  'savedQA' : Array<QAPair>,
}
export interface SyllabusContentRow {
  'contentText' : string,
  'generatedQA' : Array<QAPairRow>,
  'approvedAt' : [] | [bigint],
  'rejectionReason' : [] | [string],
  'submittedAt' : [] | [bigint],
  'chapterId' : string,
  'userProvidedQuestions' : Array<string>,
  'approvalStatus' : string,
  'savedQA' : Array<QAPairRow>,
}
export interface TeacherSubjectAssignment {
  'id' : string,
  'sectionId' : [] | [string],
  'session' : string,
  'subjectId' : string,
  'teacherId' : string,
  'classLevel' : ClassLevel,
}
export interface TeacherTimetable {
  'id' : string,
  'teacherStaffId' : string,
  'generatedAt' : bigint,
  'teacherName' : string,
  'entries' : Array<TeacherTimetableEntry>,
  'sessionId' : string,
}
export interface TeacherTimetableEntry {
  'startTime' : string,
  'endTime' : string,
  'subjectName' : string,
  'sectionName' : string,
  'dayOfWeek' : string,
  'periodNumber' : bigint,
  'className' : string,
}
export interface TimetableCellRef {
  'dayOfWeek' : string,
  'classId' : string,
  'periodNumber' : bigint,
}
export interface TransportRoute {
  'id' : string,
  'driverMobile' : string,
  'routeName' : string,
  'routeNo' : string,
  'busNo' : string,
  'capacity' : bigint,
  'driverName' : string,
}
export interface UpiPaymentSubmission {
  'status' : string,
  'studentId' : string,
  'submittedAt' : string,
  'utrNumber' : string,
  'amount' : bigint,
  'verifiedAt' : [] | [string],
  'verifiedBy' : [] | [string],
}
export interface UserAccount {
  'id' : string,
  'permissions' : Array<string>,
  'studentId' : [] | [string],
  'username' : string,
  'staffId' : [] | [string],
  'createdAt' : bigint,
  'role' : string,
  'fullName' : string,
  'isActive' : boolean,
  'sectionId' : [] | [string],
  'classLevel' : [] | [ClassLevel],
  'position' : [] | [string],
  'principalId' : string,
}
export interface UserAccountRow {
  'id' : string,
  'permissions' : Array<string>,
  'studentId' : [] | [string],
  'username' : string,
  'staffId' : [] | [string],
  'createdAt' : bigint,
  'role' : string,
  'fullName' : string,
  'isActive' : boolean,
  'sectionId' : [] | [string],
  'classLevel' : [] | [ClassLevel],
  'position' : [] | [string],
  'principalId' : string,
}
export type UserRole = { 'Driver' : null } |
  { 'Parent' : null } |
  { 'Teacher' : null } |
  { 'Student' : null } |
  { 'Admin' : null } |
  { 'Principal' : null } |
  { 'Librarian' : null } |
  { 'Accountant' : null };
export interface VirtualClass {
  'id' : string,
  'title' : string,
  'isCompleted' : boolean,
  'createdBy' : string,
  'platform' : VirtualPlatform,
  'meetingLink' : string,
  'durationMinutes' : bigint,
  'subjectId' : [] | [string],
  'classLevel' : ClassLevel,
  'scheduledAt' : string,
}
export type VirtualPlatform = { 'Zoom' : null } |
  { 'Other' : null } |
  { 'GoogleMeet' : null };
export interface _SERVICE {
  'addAlumni' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    AlumniRecord
  >,
  'addAuditLog' : ActorMethod<[string, string, string, string], AuditLog>,
  'addBook' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      bigint,
      [] | [string],
      [] | [string],
    ],
    Book
  >,
  'addChapterContent' : ActorMethod<[string, string], undefined>,
  'addExamDateToCalendar' : ActorMethod<
    [string, string, string],
    ExamCalendarEntry
  >,
  'addExpenseEntry' : ActorMethod<
    [string, bigint, string, string, [] | [string], string],
    ExpenseEntry__1
  >,
  'addExpenseEntryV2' : ActorMethod<
    [string, number, string, string, string],
    ExpenseEntry
  >,
  'addExpenseHead' : ActorMethod<
    [string, ExpHeadType, [] | [string]],
    ExpenseHead__1
  >,
  'addExpenseHeadV2' : ActorMethod<[string, string, string], ExpenseHead>,
  'addFeeHeading' : ActorMethod<
    [string, [] | [string], Array<string>],
    FeeHeading
  >,
  'addHoliday' : ActorMethod<[string, string, string, boolean], Holiday>,
  'addHomework' : ActorMethod<
    [
      ClassLevel,
      [] | [string],
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    HomeworkEntry
  >,
  'addItem' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint, bigint],
    InventoryItem
  >,
  /**
   * / Add or update an incentive for payroll purposes (alias wiring payroll incentive).
   */
  'addPayrollIncentive' : ActorMethod<
    [string, string, string, number, string],
    boolean
  >,
  'addPickupPoint' : ActorMethod<
    [string, string, string, number, bigint],
    PickupPoint
  >,
  'addResult' : ActorMethod<
    [
      string,
      string,
      Array<[string, bigint]>,
      bigint,
      number,
      string,
      [] | [bigint],
      [] | [string],
    ],
    ExamResult
  >,
  'addRoute' : ActorMethod<
    [string, string, string, string, string, bigint],
    TransportRoute
  >,
  'addStaff' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : Staff } |
      { 'err' : string }
  >,
  'addStaffIncentive' : ActorMethod<
    [string, number, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addStaffLoan' : ActorMethod<
    [string, number, number, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addStaffPayout' : ActorMethod<
    [string, number, string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'addStudent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      ClassLevel,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : Student } |
      { 'err' : string }
  >,
  'addSubjectAssignment' : ActorMethod<
    [string, string, string, [] | [string], [] | [string], string],
    { 'ok' : SubjectAssignment } |
      { 'err' : string }
  >,
  'addTransaction' : ActorMethod<
    [
      string,
      InvTxType,
      bigint,
      bigint,
      bigint,
      string,
      [] | [string],
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
    ],
    InventoryTransaction
  >,
  'approveChapter' : ActorMethod<[string], undefined>,
  'approveChapterV2' : ActorMethod<[string], undefined>,
  'archiveSession' : ActorMethod<[string], undefined>,
  'assignSubject' : ActorMethod<
    [string, ClassLevel, [] | [string], string, string],
    TeacherSubjectAssignment
  >,
  'batchSaveClassTimetables' : ActorMethod<[Array<ClassTimetable>], bigint>,
  'calculateAndSavePayroll' : ActorMethod<
    [string, bigint, bigint, bigint],
    StaffPayrollRecord
  >,
  /**
   * / Calculates the enhanced payroll for a staff member for a specific month.
   * / workingDays: total working days in that month (provided by caller / admin).
   */
  'calculateEnhancedPayroll' : ActorMethod<
    [string, string, number],
    { 'ok' : EnhancedPayrollRecord } |
      { 'err' : string }
  >,
  'calculateGrade' : ActorMethod<[number, number], string>,
  /**
   * / Calculate payroll for a staff member from attendance records.
   * / workingDays is derived from calculateWorkingDays (session start–end excluding Sundays and holidays).
   */
  'calculateStaffPayroll' : ActorMethod<
    [string, string, string, string],
    { 'ok' : FullPayrollRecord } |
      { 'err' : string }
  >,
  /**
   * / Count working days between two dates (inclusive), excluding Sundays and all stored holidays.
   */
  'calculateWorkingDays' : ActorMethod<[string, string, string], bigint>,
  'changePassword' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'checkPermission' : ActorMethod<[string, string, string], boolean>,
  /**
   * / Admin confirms a payment by UTR number (for manual GPay / UPI bank transfers).
   */
  'confirmPaymentByUtr' : ActorMethod<
    [string, string, number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'copyPasteEntireDay' : ActorMethod<[string, string, string, string], boolean>,
  'copyPasteTimetableCells' : ActorMethod<[Array<CellCopyOp>], bigint>,
  'createChapter' : ActorMethod<
    [string, bigint, string, Array<string>, string],
    SyllabusChapter
  >,
  'createChatRoom' : ActorMethod<
    [string, ChatRoomType, Array<string>, string],
    ChatRoom
  >,
  'createClassTimetable' : ActorMethod<[ClassTimetable], ClassTimetable>,
  'createExamTimetable' : ActorMethod<
    [string, string, ClassLevel, Array<ExamScheduleEntry>],
    ExamTimetable
  >,
  /**
   * / Returns a full snapshot of all stable storage as a BackupPayload.
   * / The frontend downloads this as a JSON file for safekeeping.
   */
  'createFullBackup' : ActorMethod<[], BackupPayload>,
  'createNotification' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [ClassLevel],
      string,
      string,
    ],
    Notification
  >,
  'createOnlineExam' : ActorMethod<
    [
      string,
      ClassLevel,
      [] | [string],
      bigint,
      Array<MCQQuestion>,
      [] | [string],
      [] | [string],
      string,
    ],
    OnlineExam
  >,
  'createSection' : ActorMethod<
    [ClassLevel, string, [] | [string], [] | [string]],
    { 'ok' : Section } |
      { 'err' : string }
  >,
  'createSession' : ActorMethod<[string, string, string], AcademicSession>,
  'createSmartExamTimetable' : ActorMethod<[SmartExamTimetable], bigint>,
  'createSubject' : ActorMethod<
    [string, string, ClassLevel, bigint, bigint],
    Subject
  >,
  'createUser' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [ClassLevel],
      [] | [string],
      [] | [string],
      [] | [string],
      Array<string>,
    ],
    { 'ok' : UserAccount } |
      { 'err' : string }
  >,
  'deactivateStaff' : ActorMethod<[string], undefined>,
  /**
   * / Permanently delete ALL student records — admin-only destructive operation.
   * / Clears the students map and all associated fee payments and attendance records.
   */
  'deleteAllStudents' : ActorMethod<[], undefined>,
  'deleteAlumni' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteCertificateTemplate' : ActorMethod<[string], undefined>,
  'deleteChapter' : ActorMethod<[string], undefined>,
  'deleteClassTimetable' : ActorMethod<[string], boolean>,
  'deleteExamCalendarEntry' : ActorMethod<[string], undefined>,
  'deleteExamConfig' : ActorMethod<[string], undefined>,
  'deleteExamResult' : ActorMethod<[string], undefined>,
  'deleteExamTimetable' : ActorMethod<[string], undefined>,
  'deleteExpenseEntryV2' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteExpenseHeadV2' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteFeeHeading' : ActorMethod<[string], undefined>,
  'deleteHoliday' : ActorMethod<[string], boolean>,
  'deleteHomework' : ActorMethod<[string], undefined>,
  'deleteItem' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[string], undefined>,
  'deletePickupPoint' : ActorMethod<[string], undefined>,
  'deleteRoute' : ActorMethod<[string], undefined>,
  'deleteSection' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteSmartExamTimetable' : ActorMethod<[bigint], boolean>,
  'deleteStaffIncentive' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteStaffPayout' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Permanently delete a student record. Intended for admin use only.
   * / Also removes associated fee payments and attendance records.
   */
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteSubject' : ActorMethod<[string], undefined>,
  'deleteSubjectAssignment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'discontinueStudent' : ActorMethod<[string], undefined>,
  'enrollStudentFace' : ActorMethod<
    [string, string, string, [] | [string], string, string],
    { 'ok' : FaceEnrollmentRecord } |
      { 'err' : string }
  >,
  'ensureClassGroupsExist' : ActorMethod<
    [Array<ClassLevelV>, Array<string>],
    Array<RoomRec>
  >,
  'ensureRouteGroupsExist' : ActorMethod<
    [Array<{ 'id' : string, 'name' : string }>],
    Array<RoomRec>
  >,
  /**
   * / Factory reset — clears ALL data collections and re-seeds defaults.
   * / School settings (name, address, logo) are preserved.
   * / Admin-only: callers must pass the admin password as a guard.
   */
  'factoryReset' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'generateChapterQA' : ActorMethod<
    [string, string, Array<string>],
    Array<QAPair>
  >,
  'generateClassTimetable' : ActorMethod<
    [
      GenerateTimetableParams,
      Array<[string, string, [] | [string], string]>,
      Array<[string, string]>,
      Array<[string, string]>,
    ],
    ClassTimetable
  >,
  'generatePayroll' : ActorMethod<
    [string, string, string, bigint, bigint, bigint, bigint, bigint, string],
    PayrollRecord
  >,
  'generateQAFromContent' : ActorMethod<[string, Array<string>], Array<QAPair>>,
  'generateSmartExamSchedule' : ActorMethod<
    [GenerateScheduleParams],
    Array<SmartTimetableEntry>
  >,
  'generateTeacherTimetable' : ActorMethod<[string], Array<TeacherTimetable>>,
  /**
   * / Academic calendar stats for a session: total days, sundays, holidays, working days.
   */
  'getAcademicCalendarStats' : ActorMethod<
    [string],
    {
      'sundays' : bigint,
      'holidays' : bigint,
      'totalDays' : bigint,
      'workingDays' : bigint,
    }
  >,
  /**
   * / Migration type: old Student shape without the new optional fields.
   */
  'getAcademicPerformanceReport' : ActorMethod<
    [string, string],
    AcademicPerformanceReport
  >,
  'getActiveSession' : ActorMethod<[], [] | [AcademicSession]>,
  'getAllDeviceConfigs' : ActorMethod<[], Array<DeviceConfig>>,
  'getAllExamConfigs' : ActorMethod<[string], Array<ExamConfig>>,
  'getAllFaceEnrollments' : ActorMethod<[], Array<FaceEnrollmentRecord>>,
  /**
   * / Return ALL fee payments for a session, sorted by paymentDate descending.
   * / Powers the detailed fee register view (all collectors, all classes).
   */
  'getAllFeePaymentsBySession' : ActorMethod<[string], Array<FeePayment>>,
  'getAllPayroll' : ActorMethod<[], Array<PayrollRecord>>,
  'getAllSubjectAssignments' : ActorMethod<[], Array<SubjectAssignment>>,
  /**
   * / Returns all multi-class assignment maps (for bulk loading in the UI).
   */
  'getAllSubjectClassMaps' : ActorMethod<[], Array<SubjectClassMap>>,
  /**
   * / Returns all UPI payment submissions (any status) — for admin full view.
   */
  'getAllUpiPayments' : ActorMethod<[], Array<UpiPaymentSubmission>>,
  'getAllUsers' : ActorMethod<[], Array<UserAccount>>,
  'getAlumni' : ActorMethod<[], Array<AlumniRecord>>,
  'getAppUsers' : ActorMethod<[], Array<AppUser>>,
  'getAssignmentsByClass' : ActorMethod<
    [ClassLevel],
    Array<TeacherSubjectAssignment>
  >,
  'getAssignmentsByTeacher' : ActorMethod<
    [string],
    Array<TeacherSubjectAssignment>
  >,
  'getAttendanceBreakdown' : ActorMethod<
    [string, string],
    Array<AttendanceBreakdownRow>
  >,
  'getAttendanceByDate' : ActorMethod<
    [string, string],
    Array<AttendanceRecord>
  >,
  'getAttendanceByStudent' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceSettings' : ActorMethod<[], AttendanceSystemSettings>,
  'getAttendanceSummary' : ActorMethod<
    [ClassLevel, string, string],
    { 'present' : bigint, 'late' : bigint, 'leave' : bigint, 'absent' : bigint }
  >,
  'getAttendanceSummaryToday' : ActorMethod<
    [string, string],
    AttendanceSummaryToday
  >,
  'getAuditLogs' : ActorMethod<[[] | [string], bigint], Array<AuditLog>>,
  /**
   * / Returns the auto-created credentials for a student or staff by entityId.
   * / Pass "par_<studentId>" to get the parent credentials for a student.
   */
  'getAutoCreatedCredentials' : ActorMethod<
    [string],
    [] | [{ 'username' : string, 'password' : string, 'role' : string }]
  >,
  'getBackupSettings' : ActorMethod<[], BackupSettings>,
  'getBooks' : ActorMethod<[], Array<Book>>,
  'getBusLocations' : ActorMethod<[], Array<BusLocation>>,
  'getCalendarStats' : ActorMethod<[], CalendarStats>,
  'getCertificateTemplateById' : ActorMethod<
    [string],
    [] | [CertificateTemplate__1]
  >,
  'getCertificateTemplates' : ActorMethod<[], Array<CertificateTemplate__1>>,
  'getChapterApprovalStatus' : ActorMethod<
    [string],
    { 'status' : string, 'reason' : [] | [string] }
  >,
  'getChapterContent' : ActorMethod<[string], [] | [SyllabusContent]>,
  'getChapters' : ActorMethod<[string], Array<SyllabusChapter>>,
  'getChatRooms' : ActorMethod<[[] | [string]], Array<ChatRoom>>,
  'getClassLinks' : ActorMethod<[[] | [string]], Array<ClassLinks>>,
  'getClassTimetableById' : ActorMethod<[string], [] | [ClassTimetable]>,
  'getClassTimetables' : ActorMethod<[[] | [string]], Array<ClassTimetable>>,
  'getCustomStudentColumns' : ActorMethod<
    [],
    Array<{ 'key' : string, 'columnLabel' : string, 'fieldType' : string }>
  >,
  'getDailyFeeBreakdown' : ActorMethod<
    [string, string],
    Array<FeePaymentSummary>
  >,
  'getDailySalesSummary' : ActorMethod<[], Array<DailySalesSummary>>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'feesCollectedMonth' : bigint,
      'feesCollectedToday' : bigint,
      'activeStudents' : bigint,
      'totalStudents' : bigint,
      'totalStaff' : bigint,
    }
  >,
  'getDashboardStatsV2' : ActorMethod<[string], DashboardStatsV2>,
  'getDemandRegister' : ActorMethod<
    [DemandRegisterFilter],
    Array<DemandRegisterEntry>
  >,
  'getDeviceAttendanceByDate' : ActorMethod<
    [string],
    Array<DeviceAttendanceRecord>
  >,
  'getDeviceAttendanceByDateAndType' : ActorMethod<
    [string, string],
    Array<DeviceAttendanceRecord>
  >,
  'getDeviceAttendanceByStudent' : ActorMethod<
    [bigint],
    Array<DeviceAttendanceRecord>
  >,
  'getDeviceConfig' : ActorMethod<[string], [] | [DeviceConfig]>,
  'getDirectMessages' : ActorMethod<[bigint], Array<DirectMessage>>,
  'getDirectMessagesByRecipient' : ActorMethod<[string], Array<DirectMessage>>,
  /**
   * / Returns all discontinued students (across all sessions).
   */
  'getDiscontinuedStudents' : ActorMethod<[], Array<Student>>,
  'getEnhancedPayroll' : ActorMethod<
    [string, string],
    [] | [EnhancedPayrollRecord]
  >,
  'getEnhancedPayrollByMonth' : ActorMethod<
    [string],
    Array<EnhancedPayrollRecord>
  >,
  /**
   * / Returns the count of enrolled (active) students in a class for a session.
   */
  'getEnrolledCountByClass' : ActorMethod<[ClassLevel, string], bigint>,
  /**
   * / Returns the count of enrolled (active) students in a section for a session.
   */
  'getEnrolledCountBySection' : ActorMethod<[string, string], bigint>,
  'getEnrolledStudentIds' : ActorMethod<[], Array<string>>,
  'getExamConfigs' : ActorMethod<[string, string], Array<ExamConfig>>,
  'getExamDatesForCalendar' : ActorMethod<[], Array<ExamCalendarEntry>>,
  'getExamResultsByClass' : ActorMethod<
    [string, string, string],
    Array<ExamResultV2>
  >,
  'getExamResultsByExam' : ActorMethod<[string], Array<ExamResultV2>>,
  'getExamResultsByStudent' : ActorMethod<
    [string, string],
    Array<ExamResultV2>
  >,
  'getExamSubmissions' : ActorMethod<[string], Array<OnlineExamSubmission>>,
  'getExamTimetables' : ActorMethod<[], Array<ExamTimetable>>,
  'getExpenseEntries' : ActorMethod<[[] | [string]], Array<ExpenseEntry__1>>,
  'getExpenseEntriesV2' : ActorMethod<[[] | [string]], Array<ExpenseEntry>>,
  'getExpenseHeads' : ActorMethod<[], Array<ExpenseHead__1>>,
  'getExpenseHeadsV2' : ActorMethod<[], Array<ExpenseHead>>,
  'getExpenseStats' : ActorMethod<[], ExpenseStats>,
  'getFaceAttendanceByDate' : ActorMethod<
    [string],
    Array<FaceEnrollmentRecord>
  >,
  'getFaceEnrolledStudents' : ActorMethod<[], Array<FaceEnrollmentRecord>>,
  /**
   * / Return fee audit logs. Filter by studentId or paymentId (both optional).
   */
  'getFeeAuditLogs' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<FeeAuditLog>
  >,
  'getFeeHeadings' : ActorMethod<[], Array<FeeHeading>>,
  'getFeePaymentsByCollector' : ActorMethod<[string], Array<FeePaymentEntry>>,
  /**
   * / Return all payments for a student across all sessions (for receipt history).
   */
  'getFeePaymentsByStudent' : ActorMethod<[string], Array<FeePayment>>,
  'getFeePlan' : ActorMethod<
    [ClassLevel, [] | [string], string],
    [] | [FeePlan]
  >,
  'getFeePlans' : ActorMethod<[], Array<FeePlan>>,
  /**
   * / Return all fee payments for a session enriched with student class/section data.
   * / Used by the Fee Register detailed view.
   */
  'getFeeRegisterBySession' : ActorMethod<[string], Array<FeeRegisterEntry>>,
  'getFeeRegisterByUser' : ActorMethod<
    [],
    Array<[string, Array<FeePaymentEntry>]>
  >,
  'getFeeRegisterWithBalance' : ActorMethod<
    [string],
    Array<FeeRegisterBalanceEntry>
  >,
  /**
   * / Returns all holidays. sessionId parameter is accepted for API consistency but
   * / holidays are not session-scoped in this implementation.
   */
  'getHolidays' : ActorMethod<[[] | [string]], Array<Holiday>>,
  'getHomework' : ActorMethod<[[] | [ClassLevel]], Array<HomeworkEntry>>,
  'getIndexPageConfig' : ActorMethod<[], [] | [IndexPageConfig]>,
  'getIssuedBooks' : ActorMethod<[], Array<BookIssue>>,
  'getItems' : ActorMethod<[], Array<InventoryItem>>,
  'getLastReceiptNo' : ActorMethod<[], bigint>,
  /**
   * / Returns legacy payroll records for a staff member.
   */
  'getLegacyPayrollByStaff' : ActorMethod<[string], Array<PayrollRecord>>,
  'getMessageTemplates' : ActorMethod<[], Array<[string, string]>>,
  'getMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getNotifications' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<Notification>
  >,
  'getOnlineExam' : ActorMethod<[string], [] | [OnlineExam]>,
  'getOnlineExams' : ActorMethod<[], Array<OnlineExam>>,
  'getOverdueBooks' : ActorMethod<[], Array<BookIssue>>,
  'getPaidLeaveConfig' : ActorMethod<[], PaidLeaveConfig>,
  'getPaymentsByDate' : ActorMethod<[string], Array<FeePayment>>,
  'getPaymentsByMonth' : ActorMethod<[string], Array<FeePayment>>,
  'getPaymentsByStudent' : ActorMethod<[string], Array<FeePayment>>,
  'getPaymentsByStudentAndSession' : ActorMethod<
    [string, string],
    Array<FeePayment>
  >,
  'getPayrollByMonth' : ActorMethod<
    [bigint, bigint],
    Array<StaffPayrollRecord>
  >,
  'getPayrollByStaff' : ActorMethod<[string], Array<PayrollRecord>>,
  'getPayrollCalculation' : ActorMethod<
    [string, string, bigint, bigint, bigint, bigint],
    PayrollCalculation
  >,
  'getPayrollHistory' : ActorMethod<[string], Array<StaffPayrollRecord>>,
  /**
   * / Returns all pending UPI payment submissions (for admin verification panel).
   */
  'getPendingUpiPayments' : ActorMethod<[], Array<UpiPaymentSubmission>>,
  /**
   * / Returns all pickup points for a route, sorted by order.
   */
  'getPickupPoints' : ActorMethod<[string], Array<PickupPoint>>,
  /**
   * / Alias — same as getPickupPoints; provided for frontend clarity.
   */
  'getPickupPointsByRoute' : ActorMethod<[string], Array<PickupPoint>>,
  /**
   * / Return the student's old-balance from the session immediately prior to currentSession.
   * / Looks up studentOldBalances for any entry whose sessionId != currentSession belonging
   * / to this student; returns the most recently added one, or null if none.
   * / Collect Fees uses this to auto-populate the previous-session-due field.
   */
  'getPreviousSessionBalance' : ActorMethod<
    [string, string],
    [] | [
      { 'previousYearDue' : number, 'sessionId' : string, 'amount' : number }
    ]
  >,
  'getPromotionPreview' : ActorMethod<
    [PromClassLevel, string],
    Array<PromotionPreviewItem>
  >,
  'getPublishedChapters' : ActorMethod<
    [string, [] | [string]],
    Array<ChapterWithQA>
  >,
  'getPublishedChaptersForStudent' : ActorMethod<
    [string, string],
    Array<ChapterWithQA>
  >,
  'getResultsByExam' : ActorMethod<[string], Array<ExamResult>>,
  'getResultsByStudent' : ActorMethod<[string], Array<ExamResult>>,
  'getRolePermissions' : ActorMethod<[], Array<RolePermissions>>,
  'getRoutes' : ActorMethod<[], Array<TransportRoute>>,
  'getSchoolInfo' : ActorMethod<[], SchoolInfo>,
  /**
   * / Returns the school's UPI ID (stored in appSettings.upiId).
   */
  'getSchoolUpiId' : ActorMethod<[], [] | [string]>,
  'getSchoolWideTimetable' : ActorMethod<
    [[] | [string]],
    Array<[string, ClassTimetable]>
  >,
  'getSections' : ActorMethod<[], Array<Section>>,
  'getSectionsByClass' : ActorMethod<[ClassLevel], Array<Section>>,
  'getSessions' : ActorMethod<[], Array<AcademicSession>>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getSmartExamTimetableById' : ActorMethod<
    [bigint],
    [] | [SmartExamTimetable]
  >,
  'getSmartExamTimetables' : ActorMethod<
    [[] | [string]],
    Array<SmartExamTimetable>
  >,
  'getStaff' : ActorMethod<[], Array<Staff>>,
  'getStaffAttendanceBreakdown' : ActorMethod<[string], StaffAttBreakdown>,
  'getStaffAttendanceByDate' : ActorMethod<
    [string],
    Array<StaffAttendanceRecord>
  >,
  'getStaffAttendanceByDateAndType' : ActorMethod<
    [string, string],
    Array<StaffAttendanceRecord>
  >,
  'getStaffAttendanceByMonth' : ActorMethod<
    [string, bigint, bigint],
    Array<StaffAttendanceRecord>
  >,
  'getStaffAttendanceByStaff' : ActorMethod<
    [string],
    Array<StaffAttendanceRecord>
  >,
  'getStaffById' : ActorMethod<[string], [] | [Staff]>,
  'getStaffIncentives' : ActorMethod<[string], Array<StaffIncentive>>,
  'getStaffIncentivesByMonth' : ActorMethod<
    [string, string],
    Array<StaffIncentive>
  >,
  'getStaffLoans' : ActorMethod<[string], Array<StaffLoan>>,
  /**
   * / Returns month-by-month payment summary for a staff member.
   * / netSalary is wrapped in ?Float — frontend hides amount for non-admin roles.
   */
  'getStaffPaymentSummary' : ActorMethod<
    [string],
    Array<StaffPaymentSummaryEntry>
  >,
  'getStaffPayouts' : ActorMethod<[string], Array<StaffPayout>>,
  'getStaffPayoutsByMonth' : ActorMethod<[string, string], Array<StaffPayout>>,
  'getStaffSalary' : ActorMethod<[string], [] | [number]>,
  'getStaffYearEndSummary' : ActorMethod<[string, string], StaffYearEndSummary>,
  /**
   * / Look up a student by admission number. Used by frontend to check duplicates before bulk import.
   */
  'getStudentByAdmNo' : ActorMethod<[string], [] | [Student]>,
  'getStudentById' : ActorMethod<[string], [] | [Student]>,
  'getStudentCount' : ActorMethod<[], bigint>,
  'getStudentCustomData' : ActorMethod<[string], Array<[string, string]>>,
  'getStudentDiscounts' : ActorMethod<[string], Array<StudentDiscount>>,
  'getStudentFaceEnrollment' : ActorMethod<
    [string],
    [] | [FaceEnrollmentRecord]
  >,
  'getStudentFeeBalance' : ActorMethod<
    [string, string],
    { 'previousYearDue' : number, 'oldBalance' : number }
  >,
  'getStudentFeeCollectionData' : ActorMethod<
    [string, string],
    StudentFeeCollectionData
  >,
  /**
   * / Returns 0 until inventory per-student due tracking is wired.
   */
  'getStudentInventoryDue' : ActorMethod<[string], bigint>,
  'getStudentOldBalance' : ActorMethod<
    [string, string],
    [] | [StudentOldBalance]
  >,
  'getStudentOldBalances' : ActorMethod<[string], Array<StudentOldBalance>>,
  /**
   * / Return the monthly transport fare for a student based on their assigned pickup point.
   * / Returns 0 if no pickup point is assigned or the pickup point is not found.
   */
  'getStudentTransportFare' : ActorMethod<[string], number>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getStudentsByClass' : ActorMethod<[ClassLevel], Array<Student>>,
  /**
   * / Returns all active students in a class for a given session.
   */
  'getStudentsByClassAndSession' : ActorMethod<
    [ClassLevel, string],
    Array<Student>
  >,
  'getStudentsByFamily' : ActorMethod<[string], Array<Student>>,
  /**
   * / Returns all active students assigned to a transport route for a session.
   */
  'getStudentsByRoute' : ActorMethod<[string, string], Array<Student>>,
  /**
   * / Returns all active students on a route with their pickup point details joined.
   * / Used for the route double-click page and fee collection (pickup point → monthly fare).
   */
  'getStudentsWithPickupPointsByRoute' : ActorMethod<
    [string, string],
    Array<StudentWithPickupPoint>
  >,
  'getSubjectAssignments' : ActorMethod<[string], Array<SubjectAssignment>>,
  /**
   * / Returns the multi-class assignment for a subject.
   */
  'getSubjectClassMap' : ActorMethod<[string], [] | [SubjectClassMap]>,
  /**
   * / Returns the assigned class levels for a single subject (by subject ID).
   */
  'getSubjectClassMapById' : ActorMethod<[string], [] | [Array<ClassLevel>]>,
  /**
   * / Returns all multi-class assignment maps — alias used by frontend bulk loader.
   */
  'getSubjectClassMapRecord' : ActorMethod<[], Array<SubjectClassMap>>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'getSubjectsByClass' : ActorMethod<[ClassLevel], Array<Subject>>,
  'getSubmissions' : ActorMethod<[string], Array<HomeworkSubmission>>,
  'getSyllabusContent' : ActorMethod<[string], [] | [SyllabusContent]>,
  'getTeacherTimetables' : ActorMethod<[string], Array<TeacherTimetable>>,
  'getTemplates' : ActorMethod<[], Array<CertificateTemplate>>,
  'getTemplatesByType' : ActorMethod<[string], Array<CertificateTemplate>>,
  'getTotalDueByStudentAndSession' : ActorMethod<
    [string, string],
    { 'totalFees' : bigint, 'totalPaid' : bigint, 'totalDue' : bigint }
  >,
  'getTransactions' : ActorMethod<[[] | [string]], Array<InventoryTransaction>>,
  'getTransactionsByDate' : ActorMethod<
    [string],
    Array<
      {
        'id' : string,
        'itemId' : string,
        'balanceAmount' : bigint,
        'transactionType' : { 'Sale' : null } |
          { 'Purchase' : null } |
          { 'Adjustment' : null },
        'date' : string,
        'createdBy' : string,
        'receivedAmount' : bigint,
        'sellerName' : string,
        'totalAmount' : bigint,
        'quantity' : bigint,
        'buyerAdmNo' : string,
        'buyerName' : string,
        'unitPrice' : bigint,
        'remarks' : [] | [string],
      }
    >
  >,
  'getUnreadCount' : ActorMethod<[[] | [string]], bigint>,
  /**
   * / Returns all UPI payment submissions for a specific student.
   */
  'getUpiPaymentsByStudent' : ActorMethod<
    [string],
    Array<UpiPaymentSubmission>
  >,
  'getUser' : ActorMethod<[string], [] | [UserAccount]>,
  'getUserByPrincipal' : ActorMethod<[string], [] | [UserAccount]>,
  'getUserPermissions' : ActorMethod<[string], Array<ModulePermission>>,
  'getUsers' : ActorMethod<[], Array<UserAccount>>,
  'getVirtualClasses' : ActorMethod<[[] | [ClassLevel]], Array<VirtualClass>>,
  /**
   * / Records a GPay payment confirmation (called after frontend polls for status
   * / or receives a callback). Marks the submission as confirmed.
   */
  'handleGPayCallback' : ActorMethod<
    [string, string, string, string, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Generates a UPI deep-link for GPay / any UPI app.
   * / Returns: upi://pay?pa=UPIID&pn=SCHOOLNAME&am=AMOUNT&cu=INR&tn=FeePayment
   */
  'initiateGPayPayment' : ActorMethod<
    [string, number, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'isFaceEnrolled' : ActorMethod<[string], boolean>,
  'issueBook' : ActorMethod<[string, string, string, string], BookIssue>,
  'lockPayrollMonth' : ActorMethod<
    [string, bigint, bigint],
    [] | [StaffPayrollRecord]
  >,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : { 'username' : string, 'userId' : bigint, 'role' : string } } |
      { 'err' : string }
  >,
  'markAttendance' : ActorMethod<
    [
      ClassLevel,
      string,
      string,
      string,
      Array<
        {
          'status' : AttendanceStatus,
          'studentId' : string,
          'remarks' : [] | [string],
        }
      >,
    ],
    undefined
  >,
  'markDeviceOut' : ActorMethod<[bigint, string], boolean>,
  'markFaceAttendance' : ActorMethod<
    [string, string, string, string, string, string, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'markStaffAttendanceOut' : ActorMethod<[bigint, string], boolean>,
  'promoteAllClasses' : ActorMethod<[string, string], PromotionAllResult>,
  'promoteBulkStudents' : ActorMethod<
    [PromClassLevel, string, string, [] | [string]],
    PromotionResult
  >,
  'pushActivityEntry' : ActorMethod<[string, string, string], undefined>,
  /**
   * / Update only the lastBackupTimestamp (called after a successful backup export).
   */
  'recordBackupTimestamp' : ActorMethod<[bigint], undefined>,
  'recordDeviceAttendance' : ActorMethod<[DeviceAttendanceRecord], bigint>,
  /**
   * / Alias kept for backward compat — recordPayment is the canonical name.
   * / Accepts `collectedBy` field name (same as createdBy internally).
   */
  'recordFeePayment' : ActorMethod<
    [
      string,
      string,
      string,
      Array<FeePaymentItem>,
      [] | [OtherFee],
      bigint,
      bigint,
      bigint,
      string,
      string,
      [] | [string],
      [] | [string],
      bigint,
      bigint,
      number,
    ],
    FeePayment
  >,
  'recordPayment' : ActorMethod<
    [
      string,
      string,
      string,
      Array<FeePaymentItem>,
      [] | [OtherFee],
      bigint,
      bigint,
      string,
      [] | [string],
      [] | [string],
      string,
      [] | [bigint],
      [] | [bigint],
      [] | [number],
    ],
    FeePayment
  >,
  'recordPayrollPayout' : ActorMethod<
    [string, bigint, bigint, bigint, bigint],
    [] | [StaffPayrollRecord]
  >,
  'recordStaffAttendance' : ActorMethod<
    [string, string, string, bigint, bigint, string, string],
    bigint
  >,
  'rejectChapter' : ActorMethod<[string, string], undefined>,
  'rejectChapterV2' : ActorMethod<[string, string], undefined>,
  'removeAssignment' : ActorMethod<[string], undefined>,
  'removeStudentDiscount' : ActorMethod<[string], undefined>,
  'resetUserPassword' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'resetUserPasswordAdmin' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Merge-restores all entities from a backup payload.
   * / Strategy: if ID exists → overwrite, if not → insert.  No data is deleted.
   * / Validates required fields before each write; skips invalid records and
   * / collects per-entity errors.  Continues even when one entity type fails.
   */
  'restoreFromBackup' : ActorMethod<[BackupPayload], RestoreResult>,
  'returnBook' : ActorMethod<[string, string, bigint], undefined>,
  'revokeFaceEnrollment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'revokeStudentFaceEnrollment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'saveAttendanceSettings' : ActorMethod<[AttendanceSystemSettings], undefined>,
  'saveBackupSettings' : ActorMethod<[BackupSettings], undefined>,
  'saveCertificateTemplate' : ActorMethod<
    [string, string, string, string, string, boolean, string],
    CertificateTemplate__1
  >,
  'saveChapterQA' : ActorMethod<
    [string, Array<QAPair>, Array<string>],
    undefined
  >,
  'saveClassLinks' : ActorMethod<[Array<ClassLinks>], bigint>,
  'saveCustomStudentColumns' : ActorMethod<
    [Array<{ 'key' : string, 'columnLabel' : string, 'fieldType' : string }>],
    undefined
  >,
  'saveDeviceConfig' : ActorMethod<
    [
      string,
      {
        'port' : [] | [bigint],
        'usbPort' : [] | [string],
        'deviceId' : [] | [string],
        'ipAddress' : [] | [string],
      },
    ],
    undefined
  >,
  'saveExamConfig' : ActorMethod<
    [string, string, string, Array<ExamSubjectConfig>, boolean, number],
    ExamConfig
  >,
  'saveExamMarks' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<
        {
          'subjectName' : string,
          'marksObtained' : number,
          'subjectId' : string,
          'maxMarks' : number,
          'passingMarks' : number,
        }
      >,
      [] | [bigint],
      [] | [string],
    ],
    { 'ok' : ExamResultV2 } |
      { 'err' : string }
  >,
  'saveIndexPageConfig' : ActorMethod<[IndexPageConfig], undefined>,
  /**
   * / Save (persist) a full payroll record to stable storage.
   */
  'savePayrollRecord' : ActorMethod<
    [string, string, string, string, number, bigint, bigint, number, string],
    boolean
  >,
  'saveTeacherTimetables' : ActorMethod<[Array<TeacherTimetable>], bigint>,
  'saveTemplate' : ActorMethod<
    [string, string, string, string],
    CertificateTemplate
  >,
  'scheduleVirtualClass' : ActorMethod<
    [
      string,
      ClassLevel,
      [] | [string],
      VirtualPlatform,
      string,
      string,
      bigint,
      string,
    ],
    VirtualClass
  >,
  'sendDirectMessage' : ActorMethod<[DirectMessage], DirectMessage>,
  'sendMessage' : ActorMethod<
    [string, string, string, [] | [string]],
    ChatMessage
  >,
  'setActiveSession' : ActorMethod<[string], undefined>,
  'setAppUserActive' : ActorMethod<[string, boolean], boolean>,
  'setBusActive' : ActorMethod<[string, boolean], undefined>,
  'setChapterClassLevel' : ActorMethod<[string, string], undefined>,
  'setDefaultCertificateTemplate' : ActorMethod<[string], undefined>,
  'setDefaultTemplate' : ActorMethod<[string], undefined>,
  'setFeePlan' : ActorMethod<
    [ClassLevel, [] | [string], string, Array<[string, bigint]>],
    FeePlan
  >,
  'setPaidLeaveConfig' : ActorMethod<[number], PaidLeaveConfig>,
  /**
   * / Sets the school's UPI ID (convenience wrapper around updateSettings).
   */
  'setSchoolUpiId' : ActorMethod<[string], undefined>,
  'setStudentDiscount' : ActorMethod<
    [string, string, bigint, [] | [string]],
    StudentDiscount
  >,
  'setStudentOldBalance' : ActorMethod<
    [string, string, number, [] | [number]],
    StudentOldBalance
  >,
  'submitChapterForApproval' : ActorMethod<[string], undefined>,
  'submitChapterForApprovalV2' : ActorMethod<[string], undefined>,
  'submitExam' : ActorMethod<
    [string, string, Array<[string, bigint]>, bigint],
    OnlineExamSubmission
  >,
  'submitHomework' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    HomeworkSubmission
  >,
  /**
   * / Student or parent submits a UPI payment with UTR for admin verification.
   */
  'submitUpiPayment' : ActorMethod<
    [string, bigint, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateAlumni' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateBook' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      bigint,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateBusLocation' : ActorMethod<
    [string, string, number, number],
    undefined
  >,
  'updateChapterProgress' : ActorMethod<[string, bigint], undefined>,
  'updateClassTimetable' : ActorMethod<[string, ClassTimetable], boolean>,
  'updateExamTimetable' : ActorMethod<
    [string, string, string, ClassLevel, Array<ExamScheduleEntry>],
    undefined
  >,
  'updateExpenseEntryV2' : ActorMethod<
    [string, string, number, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateExpenseHead' : ActorMethod<
    [string, string, ExpHeadType, [] | [string]],
    undefined
  >,
  'updateExpenseHeadV2' : ActorMethod<
    [string, string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateFeeHeading' : ActorMethod<
    [string, string, [] | [string], boolean, Array<string>],
    undefined
  >,
  /**
   * / Update editable fields on a fee payment and create an audit log entry for each changed field.
   */
  'updateFeePayment' : ActorMethod<
    [string, FeePaymentUpdate, string, string],
    boolean
  >,
  'updateHoliday' : ActorMethod<
    [string, string, string, string, boolean],
    boolean
  >,
  'updateHomework' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'updateItem' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateLoanRepayment' : ActorMethod<
    [string, number],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateMessageDeliveryStatus' : ActorMethod<[string, string], boolean>,
  'updateMessageTemplate' : ActorMethod<[string, string], undefined>,
  'updateOnlineExam' : ActorMethod<
    [
      string,
      string,
      ClassLevel,
      [] | [string],
      bigint,
      Array<MCQQuestion>,
      [] | [string],
      [] | [string],
      boolean,
    ],
    undefined
  >,
  'updatePayment' : ActorMethod<
    [
      string,
      string,
      Array<FeePaymentItem>,
      [] | [OtherFee],
      bigint,
      string,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updatePayrollStatus' : ActorMethod<
    [string, PayrollStatus, [] | [string]],
    undefined
  >,
  'updatePermissions' : ActorMethod<[string, Array<string>], undefined>,
  'updatePickupPoint' : ActorMethod<
    [string, string, string, number, bigint],
    undefined
  >,
  'updateResult' : ActorMethod<
    [
      string,
      Array<[string, bigint]>,
      bigint,
      number,
      string,
      [] | [bigint],
      [] | [string],
    ],
    undefined
  >,
  'updateRolePermissions' : ActorMethod<
    [UserRole, Array<ModulePermission>],
    undefined
  >,
  'updateRoute' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    undefined
  >,
  'updateSchoolInfo' : ActorMethod<[SchoolInfo], undefined>,
  'updateSection' : ActorMethod<
    [string, ClassLevel, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
  'updateSmartExamTimetable' : ActorMethod<
    [bigint, SmartExamTimetable],
    boolean
  >,
  'updateStaff' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateStaffSalary' : ActorMethod<
    [string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateStudent' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      ClassLevel,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updateStudentCustomData' : ActorMethod<
    [string, Array<[string, string]>],
    undefined
  >,
  'updateSubject' : ActorMethod<
    [string, string, string, ClassLevel, bigint, bigint],
    undefined
  >,
  'updateSubjectAssignment' : ActorMethod<
    [string, string, string, [] | [string], [] | [string], string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  /**
   * / Update the list of classes this subject is assigned to (multi-class assignment).
   */
  'updateSubjectClasses' : ActorMethod<
    [string, Array<ClassLevel>],
    [] | [SubjectClassMap]
  >,
  'updateUser' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [ClassLevel],
      [] | [string],
      [] | [string],
      [] | [string],
      boolean,
    ],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateVirtualClass' : ActorMethod<
    [string, string, string, string, bigint, boolean],
    undefined
  >,
  'upsertAppUser' : ActorMethod<[string, string, string, boolean], bigint>,
  /**
   * / Admin verifies a UPI payment and records it as a fee payment.
   */
  'verifyUpiPayment' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];